import { Trade, BrokerAccount } from "./types";

export const initialBrokerAccounts: BrokerAccount[] = [
  {
    id: "acc-1",
    name: "Apex Prop 100K Fund",
    platform: "MetaTrader 5",
    accountNumber: "MT5-8849201",
    server: "ApexFund-Live03",
    status: "Connected",
    balance: 104850.25,
    equity: 105210.80,
    lastSync: "Just now (Live WebSocket)",
  },
  {
    id: "acc-2",
    name: "IC Markets Raw ECN",
    platform: "cTrader",
    accountNumber: "cT-491029",
    server: "cTrader-Live-EU",
    status: "Connected",
    balance: 52400.00,
    equity: 52400.00,
    lastSync: "2 mins ago",
  },
  {
    id: "acc-3",
    name: "Interactive Brokers LLC",
    platform: "Interactive Brokers",
    accountNumber: "U9928103",
    server: "IB-Gateway-Direct",
    status: "Connected",
    balance: 245000.00,
    equity: 246800.00,
    lastSync: "10 mins ago",
  },
];

export const initialTrades: Trade[] = [
  {
    id: "TRD-101",
    ticker: "NAS100",
    assetClass: "Indices",
    direction: "LONG",
    entryDate: "2026-08-28 14:32",
    exitDate: "2026-08-28 16:15",
    session: "New York",
    entryPrice: 19820.50,
    exitPrice: 19965.25,
    stopLoss: 19780.00,
    takeProfit: 19970.00,
    positionSize: 5.0,
    grossPnL: 3618.75,
    netPnL: 3573.75,
    commission: 45.00,
    swap: 0.00,
    slippagePips: 0.8,
    spreadPips: 1.2,
    rMultiple: 3.57,
    strategy: "ICT Silver Bullet",
    setup: "Fair Value Gap",
    mistakeTags: [],
    marketCondition: "Trending Bullish",
    emotion: {
      confidence: 5,
      stress: 2,
      discipline: 5,
      preTradeState: "Focused",
      postTradeState: "Satisfied",
      notes: "Clean NY AM session delivery right out of the 15m bullish FVG. Held to full TP target.",
    },
    notes: "High probability setup aligning with higher timeframe daily order block.",
    timeframe: "5m",
    account: "Apex Prop 100K Fund",
  },
  {
    id: "TRD-102",
    ticker: "EUR/USD",
    assetClass: "Forex",
    direction: "SHORT",
    entryDate: "2026-08-28 08:45",
    exitDate: "2026-08-28 10:20",
    session: "London",
    entryPrice: 1.08920,
    exitPrice: 1.08480,
    stopLoss: 1.09080,
    takeProfit: 1.08450,
    positionSize: 10.0,
    grossPnL: 4400.00,
    netPnL: 4340.00,
    commission: 60.00,
    swap: 0.00,
    slippagePips: 0.2,
    spreadPips: 0.4,
    rMultiple: 2.75,
    strategy: "Judas Swing Reversal",
    setup: "Liquidity Sweep",
    mistakeTags: [],
    marketCondition: "Trending Bearish",
    emotion: {
      confidence: 4,
      stress: 2,
      discipline: 5,
      preTradeState: "Calm & Neutral",
      postTradeState: "Disciplined",
      notes: "Asian high swept at London open, instant displacement lower through previous day low.",
    },
    notes: "Executed on cTrader raw spread with zero slippage.",
    timeframe: "15m",
    account: "IC Markets Raw ECN",
  },
  {
    id: "TRD-103",
    ticker: "XAU/USD",
    assetClass: "Commodities",
    direction: "LONG",
    entryDate: "2026-08-27 15:10",
    exitDate: "2026-08-27 15:42",
    session: "New York",
    entryPrice: 2512.40,
    exitPrice: 2504.10,
    stopLoss: 2505.00,
    takeProfit: 2530.00,
    positionSize: 4.0,
    grossPnL: -3320.00,
    netPnL: -3380.00,
    commission: 60.00,
    swap: 0.00,
    slippagePips: 2.1,
    spreadPips: 2.5,
    rMultiple: -1.00,
    strategy: "Breakout & Momentum",
    setup: "Breakout & Retest",
    mistakeTags: ["FOMO", "Chased Entry"],
    marketCondition: "High Volatility (News)",
    emotion: {
      confidence: 3,
      stress: 5,
      discipline: 2,
      preTradeState: "Anxious",
      postTradeState: "Frustrated",
      notes: "Chased Gold after red folder CPI print. Entered late at the candle peak and got wicked out.",
    },
    notes: "Classic FOMO error. Must wait for 5m candle close next time.",
    timeframe: "1m",
    account: "Apex Prop 100K Fund",
  },
  {
    id: "TRD-104",
    ticker: "BTC/USD",
    assetClass: "Crypto",
    direction: "LONG",
    entryDate: "2026-08-26 19:30",
    exitDate: "2026-08-27 06:10",
    session: "Asia / Tokyo",
    entryPrice: 62450.00,
    exitPrice: 64820.00,
    stopLoss: 61800.00,
    takeProfit: 65000.00,
    positionSize: 2.5,
    grossPnL: 5925.00,
    netPnL: 5885.00,
    commission: 40.00,
    swap: -12.50,
    slippagePips: 5.0,
    spreadPips: 1.0,
    rMultiple: 3.65,
    strategy: "Order Flow Liquidity",
    setup: "Order Block Bounce",
    mistakeTags: [],
    marketCondition: "Trending Bullish",
    emotion: {
      confidence: 5,
      stress: 1,
      discipline: 5,
      preTradeState: "Focused",
      postTradeState: "Satisfied",
      notes: "Strong institutional accumulation around 62k support block. Overnight swing executed perfectly.",
    },
    notes: "Overnight swing hold with trailing stop into Asian session high.",
    timeframe: "1h",
    account: "Interactive Brokers LLC",
  },
  {
    id: "TRD-105",
    ticker: "GBP/JPY",
    assetClass: "Forex",
    direction: "SHORT",
    entryDate: "2026-08-26 09:15",
    exitDate: "2026-08-26 11:30",
    session: "London",
    entryPrice: 194.550,
    exitPrice: 193.720,
    stopLoss: 194.950,
    takeProfit: 193.500,
    positionSize: 6.0,
    grossPnL: 3410.50,
    netPnL: 3375.50,
    commission: 35.00,
    swap: 0.00,
    slippagePips: 0.5,
    spreadPips: 1.1,
    rMultiple: 2.07,
    strategy: "Asian Range Sweep",
    setup: "Liquidity Sweep",
    mistakeTags: ["Early Exit"],
    marketCondition: "Trending Bearish",
    emotion: {
      confidence: 4,
      stress: 3,
      discipline: 3,
      preTradeState: "Focused",
      postTradeState: "Regretful",
      notes: "Closed position manually 20 pips before the final 4H liquidity pool because of sudden wick.",
    },
    notes: "Should have let full TP hit. Left another +1.2R on the table.",
    timeframe: "15m",
    account: "IC Markets Raw ECN",
  },
  {
    id: "TRD-106",
    ticker: "US30",
    assetClass: "Indices",
    direction: "SHORT",
    entryDate: "2026-08-25 15:45",
    exitDate: "2026-08-25 17:00",
    session: "New York",
    entryPrice: 41250.00,
    exitPrice: 41380.00,
    stopLoss: 41380.00,
    takeProfit: 40950.00,
    positionSize: 8.0,
    grossPnL: -1040.00,
    netPnL: -1095.00,
    commission: 55.00,
    swap: 0.00,
    slippagePips: 1.5,
    spreadPips: 2.0,
    rMultiple: -1.00,
    strategy: "Mean Reversion",
    setup: "Breakout & Retest",
    mistakeTags: ["Moved Stop Loss"],
    marketCondition: "Trending Bullish",
    emotion: {
      confidence: 2,
      stress: 5,
      discipline: 1,
      preTradeState: "Anxious",
      postTradeState: "Frustrated",
      notes: "Widened stop loss during trade by 40 points hoping for reversal. Ended up taking larger loss.",
    },
    notes: "Violated rule #1: Never move stop loss away from market.",
    timeframe: "5m",
    account: "Apex Prop 100K Fund",
  },
  {
    id: "TRD-107",
    ticker: "ETH/USD",
    assetClass: "Crypto",
    direction: "LONG",
    entryDate: "2026-08-24 13:00",
    exitDate: "2026-08-24 16:30",
    session: "London/NY Overlap",
    entryPrice: 2680.00,
    exitPrice: 2795.00,
    stopLoss: 2640.00,
    takeProfit: 2800.00,
    positionSize: 25.0,
    grossPnL: 2875.00,
    netPnL: 2835.00,
    commission: 40.00,
    swap: 0.00,
    slippagePips: 0.5,
    spreadPips: 0.8,
    rMultiple: 2.88,
    strategy: "ICT Silver Bullet",
    setup: "Fair Value Gap",
    mistakeTags: [],
    marketCondition: "Trending Bullish",
    emotion: {
      confidence: 5,
      stress: 1,
      discipline: 5,
      preTradeState: "Calm & Neutral",
      postTradeState: "Satisfied",
      notes: "Textbook 15m displacement into NY open. Clean execution.",
    },
    notes: "High convicton trade based on ETH/BTC pair breakout.",
    timeframe: "15m",
    account: "Interactive Brokers LLC",
  },
  {
    id: "TRD-108",
    ticker: "AUD/USD",
    assetClass: "Forex",
    direction: "LONG",
    entryDate: "2026-08-22 02:30",
    exitDate: "2026-08-22 07:15",
    session: "Asia / Tokyo",
    entryPrice: 0.67150,
    exitPrice: 0.67580,
    stopLoss: 0.66980,
    takeProfit: 0.67600,
    positionSize: 8.0,
    grossPnL: 3440.00,
    netPnL: 3390.00,
    commission: 50.00,
    swap: 0.00,
    slippagePips: 0.1,
    spreadPips: 0.5,
    rMultiple: 2.53,
    strategy: "Asian Range Sweep",
    setup: "Liquidity Sweep",
    mistakeTags: [],
    marketCondition: "Consolidation",
    emotion: {
      confidence: 4,
      stress: 2,
      discipline: 5,
      preTradeState: "Focused",
      postTradeState: "Satisfied",
      notes: "RBA rate hold announcement created quick liquidity grab below Asian low.",
    },
    notes: "Flawless risk to reward execution.",
    timeframe: "15m",
    account: "IC Markets Raw ECN",
  },
  {
    id: "TRD-109",
    ticker: "NAS100",
    assetClass: "Indices",
    direction: "SHORT",
    entryDate: "2026-08-21 15:30",
    exitDate: "2026-08-21 16:45",
    session: "New York",
    entryPrice: 19910.00,
    exitPrice: 19740.00,
    stopLoss: 19970.00,
    takeProfit: 19720.00,
    positionSize: 6.0,
    grossPnL: 5100.00,
    netPnL: 5040.00,
    commission: 60.00,
    swap: 0.00,
    slippagePips: 1.0,
    spreadPips: 1.5,
    rMultiple: 2.83,
    strategy: "ICT Silver Bullet",
    setup: "Fair Value Gap",
    mistakeTags: [],
    marketCondition: "Trending Bearish",
    emotion: {
      confidence: 5,
      stress: 2,
      discipline: 5,
      preTradeState: "Focused",
      postTradeState: "Disciplined",
      notes: "PM session macro distribution model. High volume selloff.",
    },
    notes: "Followed daily bias perfectly.",
    timeframe: "5m",
    account: "Apex Prop 100K Fund",
  },
  {
    id: "TRD-110",
    ticker: "SOL/USD",
    assetClass: "Crypto",
    direction: "LONG",
    entryDate: "2026-08-20 14:00",
    exitDate: "2026-08-20 14:25",
    session: "London/NY Overlap",
    entryPrice: 148.20,
    exitPrice: 142.10,
    stopLoss: 144.00,
    takeProfit: 160.00,
    positionSize: 100.0,
    grossPnL: -610.00,
    netPnL: -635.00,
    commission: 25.00,
    swap: 0.00,
    slippagePips: 0.4,
    spreadPips: 0.2,
    rMultiple: -1.00,
    strategy: "Breakout & Momentum",
    setup: "Breakout & Retest",
    mistakeTags: ["Overleveraged"],
    marketCondition: "Range-Bound / Choppy",
    emotion: {
      confidence: 3,
      stress: 4,
      discipline: 2,
      preTradeState: "Overconfident",
      postTradeState: "Frustrated",
      notes: "Sized too heavily on an unconfirmed 1m breakout. Stopped out rapidly.",
    },
    notes: "Position size was 2x the standard risk model.",
    timeframe: "1m",
    account: "Interactive Brokers LLC",
  },
  {
    id: "TRD-111",
    ticker: "EUR/USD",
    assetClass: "Forex",
    direction: "LONG",
    entryDate: "2026-08-19 09:00",
    exitDate: "2026-08-19 12:15",
    session: "London",
    entryPrice: 1.08200,
    exitPrice: 1.08640,
    stopLoss: 1.08050,
    takeProfit: 1.08650,
    positionSize: 12.0,
    grossPnL: 5280.00,
    netPnL: 5210.00,
    commission: 70.00,
    swap: 0.00,
    slippagePips: 0.1,
    spreadPips: 0.3,
    rMultiple: 2.93,
    strategy: "Judas Swing Reversal",
    setup: "Liquidity Sweep",
    mistakeTags: [],
    marketCondition: "Trending Bullish",
    emotion: {
      confidence: 5,
      stress: 1,
      discipline: 5,
      preTradeState: "Calm & Neutral",
      postTradeState: "Satisfied",
      notes: "London manipulation low swept previous week low and reversed sharply into London fix.",
    },
    notes: "Full TP filled with no drawdowns on trade.",
    timeframe: "15m",
    account: "IC Markets Raw ECN",
  },
  {
    id: "TRD-112",
    ticker: "USOIL",
    assetClass: "Commodities",
    direction: "SHORT",
    entryDate: "2026-08-18 16:00",
    exitDate: "2026-08-18 18:30",
    session: "New York",
    entryPrice: 76.80,
    exitPrice: 75.10,
    stopLoss: 77.40,
    takeProfit: 74.80,
    positionSize: 2000.0,
    grossPnL: 3400.00,
    netPnL: 3345.00,
    commission: 55.00,
    swap: 0.00,
    slippagePips: 0.05,
    spreadPips: 0.03,
    rMultiple: 2.83,
    strategy: "Order Flow Liquidity",
    setup: "Order Block Bounce",
    mistakeTags: [],
    marketCondition: "Trending Bearish",
    emotion: {
      confidence: 4,
      stress: 2,
      discipline: 4,
      preTradeState: "Focused",
      postTradeState: "Disciplined",
      notes: "Inventory data release caused rejection off 4H supply block.",
    },
    notes: "Solid risk management and clean partial take-profit exits.",
    timeframe: "30m",
    account: "Apex Prop 100K Fund",
  },
  {
    id: "TRD-113",
    ticker: "SPX500",
    assetClass: "Indices",
    direction: "LONG",
    entryDate: "2026-08-15 15:00",
    exitDate: "2026-08-15 16:30",
    session: "New York",
    entryPrice: 5610.20,
    exitPrice: 5648.50,
    stopLoss: 5595.00,
    takeProfit: 5650.00,
    positionSize: 4.0,
    grossPnL: 3064.00,
    netPnL: 3020.00,
    commission: 44.00,
    swap: 0.00,
    slippagePips: 0.5,
    spreadPips: 1.0,
    rMultiple: 2.52,
    strategy: "ICT Silver Bullet",
    setup: "Fair Value Gap",
    mistakeTags: [],
    marketCondition: "Trending Bullish",
    emotion: {
      confidence: 5,
      stress: 1,
      discipline: 5,
      preTradeState: "Focused",
      postTradeState: "Satisfied",
      notes: "Afternoon continuation model off 5m balanced price range.",
    },
    notes: "Executed smoothly on institutional direct feed.",
    timeframe: "5m",
    account: "Interactive Brokers LLC",
  },
  {
    id: "TRD-114",
    ticker: "USD/CAD",
    assetClass: "Forex",
    direction: "SHORT",
    entryDate: "2026-08-14 13:45",
    exitDate: "2026-08-14 14:10",
    session: "London/NY Overlap",
    entryPrice: 1.36800,
    exitPrice: 1.37050,
    stopLoss: 1.37050,
    takeProfit: 1.36200,
    positionSize: 8.0,
    grossPnL: -2000.00,
    netPnL: -2050.00,
    commission: 50.00,
    swap: 0.00,
    slippagePips: 0.2,
    spreadPips: 0.6,
    rMultiple: -1.00,
    strategy: "Breakout & Momentum",
    setup: "Breakout & Retest",
    mistakeTags: ["Chased Entry", "FOMO"],
    marketCondition: "High Volatility (News)",
    emotion: {
      confidence: 2,
      stress: 4,
      discipline: 2,
      preTradeState: "Anxious",
      postTradeState: "Regretful",
      notes: "Tried to front-run Canadian employment numbers. Whiplashed immediately.",
    },
    notes: "Remember: Never enter right before high impact news releases.",
    timeframe: "5m",
    account: "IC Markets Raw ECN",
  },
  {
    id: "TRD-115",
    ticker: "NAS100",
    assetClass: "Indices",
    direction: "LONG",
    entryDate: "2026-08-13 14:40",
    exitDate: "2026-08-13 16:10",
    session: "New York",
    entryPrice: 19680.00,
    exitPrice: 19850.00,
    stopLoss: 19620.00,
    takeProfit: 19860.00,
    positionSize: 5.0,
    grossPnL: 4250.00,
    netPnL: 4195.00,
    commission: 55.00,
    swap: 0.00,
    slippagePips: 0.7,
    spreadPips: 1.2,
    rMultiple: 2.83,
    strategy: "ICT Silver Bullet",
    setup: "Order Block Bounce",
    mistakeTags: [],
    marketCondition: "Trending Bullish",
    emotion: {
      confidence: 5,
      stress: 2,
      discipline: 5,
      preTradeState: "Calm & Neutral",
      postTradeState: "Satisfied",
      notes: "NY opening session discount bounce off 1H Bullish OB.",
    },
    notes: "Held through minor pullback with zero hesitation.",
    timeframe: "5m",
    account: "Apex Prop 100K Fund",
  },
];
